---
defaultBaseImageVersion: latest
stages:
- name: Build Back End Stage
  inputs:
  - type: git
    branch: master
    service: ${GIT_REPO}
  triggers:
  - type: commit
    events: push|pull_request
  jobs:
  - name: Build Back End Stage
    type: builder
    build_type: npm
    script: |
      #!/bin/bash
      # The default Node.js version is 0.10.40
      # To use Node.js 0.10.48, uncomment the following line:
      #export PATH=/opt/IBM/node-v0.10.48/bin:$PATH
      # To use Node.js 0.12.7, uncomment the following line:
      #export PATH=/opt/IBM/node-v0.12/bin:$PATH
      # To use Node.js 4.4.5, uncomment the following line:
      #export PATH=/opt/IBM/node-v4.4.5/bin:$PATH
      # To use Node.js 6.7.0, uncomment the following line:
      export PATH=/opt/IBM/node-v6.7.0/bin:$PATH
      #!/bin/bash
      npm install
- name: Deploy Back end Stage
  inputs:
  - type: job
    stage: Build Back End Stage
    job: Build Back End Stage
  triggers:
  - type: stage
  properties:
    - name: CF_APP_NAME
      value: ${CF_APP_NAME}
      type: text
    - name: ASSISTANT_VERSION
      value: ${ASSISTANT_VERSION}
      type: text
    - name: ASSISTANT_APIKEY
      value: ${ASSISTANT_APIKEY}
      type: text
    - name: ASSISTANT_URL
      value: ${ASSISTANT_URL}
      type: text
    - name: ASSISTANT_ID
      value: ${ASSISTANT_ID}
      type: text
  jobs:
  - name: Backend Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
      api_key: ${API_KEY}
    script: |
      #!/bin/bash
      #------ Set Env variables
      rm -rf .env
      file="assistantVersion=${ASSISTANT_VERSION}\nassistantApikey=${ASSISTANT_APIKEY}\nassistantURL=${ASSISTANT_URL}\nassistantID=${ASSISTANT_ID}"
      echo -e $file >> .env
      echo "Creating .env file with:"
      echo -e $file
      #--blue green
      echo blue green plugin
      cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
      cf install-plugin blue-green-deploy -r CF-Community -f
      #--------------
      cf blue-green-deploy ${CF_APP} --delete-old-apps
      # View logs
      cf logs "${CF_APP}" --recent