---
defaultBaseImageVersion: latest
stages:
- name: Build Front End Stage
  inputs:
  - type: git
    branch: master
    service: ${GIT_REPO}
  triggers:
  - type: commit
    events: push
  jobs:
  - name: Build Front End Stage
    type: builder
    build_type: npm
    script: |
      #!/bin/bash
      # The default Node.js version is 0.10.40
      # To use Node.js 0.10.48, uncomment the following line:
      #export PATH=/opt/IBM/node-v0.10.48/bin:$PATH
      # To use Node.js 0.12.7, uncomment the following line:
      #export PATH=/opt/IBM/node-v0.12/bin:$PATH
      # To use Node.js 4.4.5, uncomment the following line:
      #export PATH=/opt/IBM/node-v4.4.5/bin:$PATH
      # To use Node.js 6.7.0, uncomment the following line:
      export PATH=/opt/IBM/node-v6.7.0/bin:$PATH
      file="export default {API:'https://${CF_APP_NAME}-backend.mybluemix.net'}"
      echo $file > src/config/env/production.js
      echo "Creating env file with:"
      echo $file
      npm install
      npm run build
- name: Deploy Front end Stage
  inputs:
  - type: job
    stage: Build Front End Stage
    job: Build Front End Stage
  triggers:
  - type: stage
  properties:
  jobs:
  - name: Frontend Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
      api_key: ${API_KEY}
    script: |
      #!/bin/bash
      #--blue green
      echo blue green plugin
      cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
      cf install-plugin blue-green-deploy -r CF-Community -f
      #--------------
      cf blue-green-deploy ${CF_APP} --delete-old-apps